name: Build and Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test

    - name: Build gem
      run: gem build *.gemspec

    - name: Upload gem artifact
      uses: actions/upload-artifact@v3
      with:
        name: gem
        path: '*.gem'

  publish:
    needs: build
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Download gem artifact
      uses: actions/download-artifact@v3
      with:
        name: gem

    - name: Publish to RubyGems
      run: |
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :rubygems_api_key: ${RUBYGEMS_API_KEY}
        EOF
        chmod 0600 ~/.gem/credentials
        gem push *.gem
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}